"""
Django settings for GameFowl project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import logging.handlers  # noqa: F401 — ensures RotatingFileHandler is importable by LOGGING config
import os
import sys

# ---------------------------------------------------------------------------
# Python 3.14 + Django < 5.2 compatibility
# ---------------------------------------------------------------------------
# Python 3.14 made super() objects copyable, which breaks Django 5.1's
# BaseContext.__copy__ and causes AttributeError on every admin changelist.
# Fixed upstream in Django 5.2.  Remove this block after upgrading to 5.2+.
# Prefer Python 3.12 for production with Django 5.1.
if sys.version_info >= (3, 14):
    from copy import copy as _copy
    from django.template.context import BaseContext

    def _patched_base_context_copy(self):
        duplicate = BaseContext()
        duplicate.__class__ = self.__class__
        duplicate.__dict__ = _copy(self.__dict__)
        duplicate.dicts = self.dicts[:]
        return duplicate

    BaseContext.__copy__ = _patched_base_context_copy

# Load .env file if present (production uses environment variables set in the
# service manager; .env is an optional convenience for local overrides).
_env_path = Path(__file__).resolve().parent.parent / '.env'
if _env_path.exists():
    with open(_env_path) as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _k, _, _v = _line.partition('=')
                os.environ.setdefault(_k.strip(), _v.strip())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY is loaded from the DJANGO_SECRET_KEY environment variable.
# In production, set this in .env or in the NSSM service environment tab.
# To generate a new key: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-$rm$w0aqx6o&i+h9l9c&f=%evb%_xi8l6jg^p)9l7%@rs+cp1e',  # dev fallback only
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() not in ('false', '0', 'no', 'off')

_allowed = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.1.4',
    '192.168.0.63',
    '10.0.0.10',
    '192.168.0.150',
] or [h.strip() for h in _allowed.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'SmartWagers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

_csrf_origins = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS =  [
    'http://localhost',
    'http://127.0.0.1',
    'http://192.168.1.4',
    'http://192.168.0.63',
    'http://10.0.0.10',
    'http://192.168.0.150',
] or [o.strip() for o in _csrf_origins.split(',') if o.strip()]

ROOT_URLCONF = 'GameFowl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GameFowl.wsgi.application'

# Set the ASGI application
ASGI_APPLICATION = 'GameFowl.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

_database_engine = os.environ.get(
    'DJANGO_DB_ENGINE',
    'sqlite' if DEBUG else 'postgresql',
).strip().lower()

if not DEBUG and _database_engine != 'postgresql':
    from django.core.exceptions import ImproperlyConfigured as _ImproperlyConfigured
    raise _ImproperlyConfigured(
        'Production requires PostgreSQL. Set DJANGO_DB_ENGINE=postgresql and '
        'configure POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD.'
    )

if _database_engine == 'postgresql':
    _required_postgres_settings = {
        'POSTGRES_DB': os.environ.get('POSTGRES_DB', '').strip(),
        'POSTGRES_USER': os.environ.get('POSTGRES_USER', '').strip(),
        'POSTGRES_PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
    }
    _missing_postgres_settings = [
        name for name, value in _required_postgres_settings.items() if not value
    ]
    if _missing_postgres_settings:
        from django.core.exceptions import ImproperlyConfigured as _ImproperlyConfigured
        raise _ImproperlyConfigured(
            'Missing PostgreSQL settings: ' + ', '.join(_missing_postgres_settings)
        )

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _required_postgres_settings['POSTGRES_DB'],
            'USER': _required_postgres_settings['POSTGRES_USER'],
            'PASSWORD': _required_postgres_settings['POSTGRES_PASSWORD'],
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1').strip(),
            'PORT': os.environ.get('POSTGRES_PORT', '5432').strip(),
            'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '60')),
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                'connect_timeout': int(os.environ.get('POSTGRES_CONNECT_TIMEOUT', '5')),
            },
        }
    }
elif _database_engine == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.environ.get('SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    from django.core.exceptions import ImproperlyConfigured as _ImproperlyConfigured
    raise _ImproperlyConfigured(
        f'Unsupported DJANGO_DB_ENGINE={_database_engine!r}. '
        'Use "postgresql" or "sqlite".'
    )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # If you have a global static folder
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # For `collectstatic`


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
# Two rotating log files are written to <project_root>/logs/:
#   app.log   — INFO and above: business events (fights, bets, payouts, logins)
#   debug.log — DEBUG and above: everything including verbose internals
#
# The console handler mirrors debug.log so dev output is unchanged.
# ---------------------------------------------------------------------------

_LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(_LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'app': {
            'format': '{asctime} {levelname:<8} {name} — {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'verbose': {
            'format': '{asctime} {levelname:<8} {name}:{lineno} — {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'app_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(_LOG_DIR, 'app.log'),
            'maxBytes': 10 * 1024 * 1024,   # 10 MB per file
            'backupCount': 5,
            'formatter': 'app',
            'level': 'INFO',
            'encoding': 'utf-8',
        },
        'debug_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(_LOG_DIR, 'debug.log'),
            'maxBytes': 10 * 1024 * 1024,   # 10 MB per file
            'backupCount': 3,
            'formatter': 'verbose',
            'level': 'DEBUG',
            'encoding': 'utf-8',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'app',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        # All SmartWagers app loggers (views, services, consumers)
        'SmartWagers': {
            'handlers': ['app_file', 'debug_file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Django HTTP 4xx/5xx errors and security violations
        # Console is included so NSSM/daphne_stderr.log always captures 500s
        # when DEBUG=False (production).
        'django.request': {
            'handlers': ['app_file', 'debug_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['app_file', 'debug_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

#Channels
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

#LOGIN
LOGIN_URL = '/login'  # Redirect here if not authenticated
# Fallback only — RoleBasedLoginView.get_success_url() picks the role page.
# Do not use /index here: that page is display-only and 403s tellers.
LOGIN_REDIRECT_URL = '/user'

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 86400  # 24 hours (in seconds)

# Set to False, or set WAGER_RECEIPT_PRINTING_ENABLED=false in the environment,
# to register bets without requiring receipt printing.
WAGER_RECEIPT_PRINTING_ENABLED = os.getenv(
    "WAGER_RECEIPT_PRINTING_ENABLED",
    "true",
).lower() in ("1", "true", "yes", "on")

# ---------------------------------------------------------------------------
# Master lock (offline monthly activation)
# ---------------------------------------------------------------------------
# Production must set MASTER_LOCK_REQUIRED=True and supply both a signing key
# and a Django password hash of the master key (never the plaintext key).
# Generate a hash with:
#   python manage.py hash_master_lock_key
# Bootstrap state with:
#   python manage.py init_master_lock
_master_lock_required_env = os.environ.get('MASTER_LOCK_REQUIRED', '').strip().lower()
if _master_lock_required_env:
    MASTER_LOCK_REQUIRED = _master_lock_required_env in ('1', 'true', 'yes', 'on')
else:
    MASTER_LOCK_REQUIRED = not DEBUG

MASTER_LOCK_SIGNING_KEY = os.environ.get('MASTER_LOCK_SIGNING_KEY', '')
MASTER_LOCK_PASSWORD_HASH = os.environ.get('MASTER_LOCK_PASSWORD_HASH', '')
_master_lock_state = os.environ.get('MASTER_LOCK_STATE_PATH', '').strip()
if _master_lock_state:
    MASTER_LOCK_STATE_PATH = _master_lock_state
elif os.name == 'nt' and MASTER_LOCK_REQUIRED:
    MASTER_LOCK_STATE_PATH = r'C:\SmartWagers\data\master_lock.state'
else:
    MASTER_LOCK_STATE_PATH = str(BASE_DIR / 'master_lock.state')

if MASTER_LOCK_REQUIRED:
    from django.core.exceptions import ImproperlyConfigured as _ImproperlyConfigured
    if not MASTER_LOCK_SIGNING_KEY:
        raise _ImproperlyConfigured(
            'MASTER_LOCK_SIGNING_KEY must be set when MASTER_LOCK_REQUIRED is enabled.'
        )
    # MASTER_LOCK_PASSWORD_HASH is intentionally NOT required at import time so
    # `python manage.py hash_master_lock_key` can run to generate it. Runtime
    # enable/verify still refuses an empty hash when MASTER_LOCK_REQUIRED is True.

