@echo off
REM ============================================================
REM  SmartWagers — Install the local print agent on this PC
REM  Run this on each Windows cashier/teller PC.
REM
REM  What it does:
REM    1. Installs pywin32 (Windows printer driver support)
REM    2. Creates config.json from the example if not present
REM    3. Adds a silent VBS launcher to Windows Startup so the
REM       agent starts hidden when the user logs in
REM ============================================================

REM -- Check Python
python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python not found.
    echo        Install Python from https://python.org ^(check "Add to PATH"^)
    pause
    exit /b 1
)

echo Installing pywin32 for Windows printer support...
echo Using Python: 
python -c "import sys; print(sys.executable)"
python -m pip install --upgrade --force-reinstall pywin32
if errorlevel 1 (
    echo ERROR: Failed to install pywin32.
    pause
    exit /b 1
)

echo Running pywin32 post-install...
python -m pywin32_postinstall -install
if errorlevel 1 (
    echo -m pywin32_postinstall failed; trying Scripts\pywin32_postinstall.py ...
    for /f "delims=" %%S in ('python -c "import sysconfig; print(sysconfig.get_path('scripts'))"') do (
        if exist "%%S\pywin32_postinstall.py" (
            python "%%S\pywin32_postinstall.py" -install
        ) else (
            echo WARNING: pywin32_postinstall.py not found under %%S
            echo          Confirm pywin32 installed for this Python: python -m pip show pywin32
        )
    )
)

REM pythonw is what the silent launcher uses — verify the same install can import win32print
echo Verifying pywin32 import...
python -c "import win32print, win32con; print('win32print/win32con: OK')"
if errorlevel 1 (
    echo ERROR: pywin32 installed but import failed for python.
    echo Try: python -m pywin32_postinstall -install
    pause
    exit /b 1
)
python -c "import win32ui; print('win32ui: OK')"
if errorlevel 1 (
    echo.
    echo WARNING: win32ui DLL failed to load.
    echo This usually needs:
    echo   1. Microsoft Visual C++ Redistributable ^(x64^)
    echo      https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
    echo   2. Or set "print_mode": "escpos" in config.json for thermal printers
    echo      ^(escpos uses win32print only, not win32ui^)
    echo.
    pause
) else (
    echo win32ui: OK
)
where pythonw >nul 2>&1
if not errorlevel 1 (
    pythonw -c "import win32print, win32con"
    if errorlevel 1 (
        echo WARNING: pythonw cannot import pywin32. Silent start may fail.
        echo Install with: pythonw -m pip install pywin32
        pause
    ) else (
        echo pythonw: OK
    )
)

REM -- Create config.json if it does not already exist
set AGENT_DIR=%~dp0
if not exist "%AGENT_DIR%config.json" (
    echo Creating config.json from template...
    copy "%AGENT_DIR%config.example.json" "%AGENT_DIR%config.json"
    echo.
    echo ACTION REQUIRED: Open config.json and set "printer_name" to the
    echo exact Windows printer queue name for this PC's receipt printer.
    echo Leave it empty ^("printer_name": ""^) to use the Windows default printer.
    echo.
    start notepad "%AGENT_DIR%config.json"
    pause
) else (
    echo config.json already exists — skipping copy.
)

REM -- Add silent launcher to Windows Startup (no CMD window on login)
set STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup
set SHORTCUT=%STARTUP%\SmartWagers-PrintAgent.vbs
set OLD_BAT=%STARTUP%\SmartWagers-PrintAgent.bat

echo.
echo Adding print agent to Windows Startup folder (silent)...
if exist "%OLD_BAT%" del "%OLD_BAT%"
if not exist "%AGENT_DIR%start_print_agent_silent.vbs" (
    echo ERROR: start_print_agent_silent.vbs missing from %AGENT_DIR%
    pause
    exit /b 1
)
(
echo ' Auto-generated by install_print_agent.bat - runs print agent hidden
echo Set sh = CreateObject^("WScript.Shell"^)
echo sh.Run "wscript.exe //nologo ""%AGENT_DIR%start_print_agent_silent.vbs""", 0, False
) > "%SHORTCUT%"

echo.
echo Done. The print agent will start automatically on next login ^(no window^).
echo.
echo To start it now ^(background^):
echo   %AGENT_DIR%run_print_agent.bat
echo.
echo To test: open http://127.0.0.1:8765/health in a browser on this PC.
echo.
pause
