# Generated by Django 5.1 on 2025-05-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fightnum', models.IntegerField(default=0)),
                ('m_total', models.FloatField(default=0)),
                ('w_total', models.FloatField(default=0)),
                ('m_payout', models.FloatField(default=0)),
                ('w_payout', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='000000', editable=False, max_length=10, unique=True)),
                ('fightnum', models.IntegerField(default=0)),
                ('side', models.CharField(max_length=5)),
                ('wager', models.FloatField()),
                ('cashier', models.CharField(default='Atong', max_length=100)),
            ],
        ),
    ]
