# Generated by Django 5.1 on 2025-05-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0002_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totals',
            old_name='m_payout',
            new_name='mpayout',
        ),
        migrations.RenameField(
            model_name='totals',
            old_name='m_total',
            new_name='mtotal',
        ),
        migrations.RenameField(
            model_name='totals',
            old_name='w_payout',
            new_name='totalpot',
        ),
        migrations.RenameField(
            model_name='totals',
            old_name='w_total',
            new_name='wpayout',
        ),
        migrations.RenameField(
            model_name='wagers',
            old_name='transaction_id',
            new_name='transactionid',
        ),
        migrations.AddField(
            model_name='totals',
            name='wtotal',
            field=models.FloatField(default=0),
        ),
    ]
