# Generated by Django 5.1 on 2025-06-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0004_fight_results_alter_wagers_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='M_control_status',
            field=models.CharField(default='Open', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='W_control_status',
            field=models.CharField(default='Open', max_length=10),
        ),
    ]
