# Generated by Django 5.1 on 2025-06-06 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0006_fight_results_mpayout_fight_results_mtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fightnum', models.IntegerField(default=0)),
                ('overall_status', models.CharField(default='Open', max_length=10)),
                ('meron_status', models.CharField(default='Open', max_length=10)),
                ('wala_status', models.CharField(default='Open', max_length=10)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
