# Generated by Django 5.1 on 2025-06-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0007_fight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight_status',
            name='meron_status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='fight_status',
            name='overall_status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='fight_status',
            name='wala_status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='M_control_status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='W_control_status',
            field=models.CharField(default='OPEN', max_length=10),
        ),
    ]
