# Generated by Django 5.1 on 2025-06-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0008_alter_fight_status_meron_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagers',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
