# Generated by Django 5.1 on 2025-06-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0009_wagers_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wagers',
            old_name='date',
            new_name='create_at',
        ),
    ]
