# Generated by Django 5.1 on 2025-06-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0010_rename_date_wagers_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wagers',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
