# Generated by Django 5.1 on 2025-06-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0011_rename_create_at_wagers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagers',
            name='side',
            field=models.CharField(max_length=10),
        ),
    ]
