# Generated by Django 5.1 on 2025-06-13 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0012_alter_wagers_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
