# Generated by Django 5.1 on 2025-07-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0013_alter_wagers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagers',
            name='cashed_out',
            field=models.BooleanField(default=False),
        ),
    ]
