# Generated by Django 5.1 on 2026-06-12 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0016_wagers_registered"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TellerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("REMIT", "Remit"), ("COLLECT", "Collect")],
                        max_length=10,
                    ),
                ),
                ("amount", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="sessionlog",
            options={"ordering": ["-login_time"]},
        ),
        migrations.AddIndex(
            model_name="sessionlog",
            index=models.Index(
                fields=["user", "login_time"], name="SmartWagers_user_id_5fc95b_idx"
            ),
        ),
        migrations.AddField(
            model_name="tellertransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teller_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tellertransaction",
            index=models.Index(
                fields=["user", "transaction_type"],
                name="SmartWagers_user_id_5cafa5_idx",
            ),
        ),
    ]
