# Generated by Django 5.1 on 2026-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0017_tellertransaction_alter_sessionlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tellertransaction",
            name="transaction_id",
            field=models.CharField(
                default="R000000000", editable=False, max_length=12, unique=True
            ),
        ),
    ]
