# Generated by Django 5.1 on 2026-06-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0018_tellertransaction_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tellertransaction",
            name="received",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
