# Generated by Django 5.1 on 2026-06-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0021_fight_results_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tellertransaction",
            name="transaction_id",
            field=models.CharField(default="R000000", editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name="tellertransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("REMIT", "Remit"),
                    ("COLLECT", "Collect"),
                    ("PAYOUT", "Payout"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="wagers",
            name="transactionid",
            field=models.CharField(default="000000", editable=False, max_length=10),
        ),
    ]
