# Generated by Django 5.1 on 2026-07-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0023_restore_unique_transaction_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="teller_max_balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="tellertransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("REMIT", "Remit"),
                    ("COLLECT", "Borrow"),
                    ("PAYOUT", "Payout"),
                ],
                max_length=10,
            ),
        ),
    ]
