# Generated by Django 5.1 on 2026-07-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0026_tellerstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="wagers",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
