# Generated by Django 5.1 on 2026-08-01 18:48

from django.db import migrations, models
from django.utils.timezone import now


def keep_only_latest_active_event(apps, schema_editor):
    Event = apps.get_model("SmartWagers", "Event")
    active_events = Event.objects.filter(is_active=True).order_by(
        "-started_at", "-pk"
    )
    latest = active_events.first()
    if latest is not None:
        active_events.exclude(pk=latest.pk).update(
            is_active=False,
            ended_at=now(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0031_alter_fight_results_side_alter_wagers_side"),
    ]

    operations = [
        migrations.RunPython(
            keep_only_latest_active_event,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="one_active_event",
            ),
        ),
    ]
