# Generated by Django 5.1 on 2026-08-01 18:49

from django.db import migrations, models


def seed_transaction_sequences(apps, schema_editor):
    Wagers = apps.get_model("SmartWagers", "Wagers")
    TellerTransaction = apps.get_model("SmartWagers", "TellerTransaction")
    TransactionSequence = apps.get_model("SmartWagers", "TransactionSequence")

    wager_max = 0
    for transaction_id in Wagers.objects.values_list("transactionid", flat=True).iterator():
        if transaction_id and transaction_id.isdigit():
            wager_max = max(wager_max, int(transaction_id))

    teller_max = 0
    for transaction_id in TellerTransaction.objects.values_list("transaction_id", flat=True).iterator():
        if transaction_id and transaction_id.startswith("R"):
            try:
                teller_max = max(teller_max, int(transaction_id[1:]))
            except ValueError:
                continue

    TransactionSequence.objects.update_or_create(
        key="WAGER", defaults={"value": wager_max}
    )
    TransactionSequence.objects.update_or_create(
        key="TELLER", defaults={"value": teller_max}
    )


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0032_event_one_active_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionSequence",
            fields=[
                (
                    "key",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("value", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(
            seed_transaction_sequences,
            migrations.RunPython.noop,
        ),
    ]
