# Generated by Django 5.1.6 on 2026-08-04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWagers', '0033_transactionsequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TellerCloseOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fightnum', models.IntegerField()),
                ('expected_cash_on_hand', models.FloatField()),
                ('grand_total', models.FloatField(default=0)),
                ('remit_total', models.FloatField(default=0)),
                ('collect_total', models.FloatField(default=0)),
                ('payout_total', models.FloatField(default=0)),
                ('actual_cash_counted', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_close_outs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teller_close_outs', to='SmartWagers.event')),
                ('remit_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_out', to='SmartWagers.tellertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_outs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tellercloseout',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='one_close_out_per_teller_per_event'),
        ),
    ]
