# Generated by Django 5.1 on 2026-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0036_event_admin_cash_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminbanktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("BORROW", "Borrow"), ("REMIT", "Advance")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="tellertransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("REMIT", "Advance"),
                    ("COLLECT", "Borrow"),
                    ("PAYOUT", "Payout"),
                ],
                max_length=10,
            ),
        ),
    ]
