# Generated by Django 5.1 on 2026-08-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0037_alter_adminbanktransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="plasada",
            field=models.FloatField(default=0.05),
        ),
    ]
