# Generated by Django 5.1 on 2026-08-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0038_correct_plasada_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionsequence",
            name="cycle",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wagers",
            name="sequence_cycle",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="tellertransaction",
            name="sequence_cycle",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="adminbanktransaction",
            name="sequence_cycle",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="adminbanktransaction",
            name="transaction_id",
            field=models.CharField(
                blank=True, editable=False, max_length=12, null=True, unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ArchivedWager",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_pk", models.BigIntegerField(editable=False, unique=True)),
                ("sequence_cycle", models.PositiveBigIntegerField(editable=False)),
                ("transactionid", models.CharField(editable=False, max_length=10)),
                ("fightnum", models.IntegerField()),
                ("side", models.CharField(max_length=20)),
                ("wager", models.FloatField()),
                ("cashier", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField()),
                ("cashed_out", models.BooleanField(default=False)),
                ("registered", models.BooleanField(default=True)),
                ("cancelled", models.BooleanField(default=False)),
                ("client_request_id", models.CharField(blank=True, max_length=36, null=True)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="archived_wagers", to="SmartWagers.event")),
            ],
            options={
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedTellerTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_pk", models.BigIntegerField(editable=False, unique=True)),
                ("sequence_cycle", models.PositiveBigIntegerField(editable=False)),
                ("transaction_id", models.CharField(editable=False, max_length=12)),
                ("transaction_type", models.CharField(max_length=10)),
                ("amount", models.FloatField()),
                ("received", models.BooleanField(blank=True, default=None, null=True)),
                ("affects_admin_fund", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField()),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("close_out", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="archived_remit_transaction", to="SmartWagers.tellercloseout")),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="archived_teller_transactions", to="SmartWagers.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="archived_teller_transactions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="ArchivedAdminBankTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_pk", models.BigIntegerField(editable=False, unique=True)),
                ("sequence_cycle", models.PositiveBigIntegerField(editable=False)),
                ("transaction_id", models.CharField(editable=False, max_length=12)),
                ("transaction_type", models.CharField(max_length=10)),
                ("amount", models.FloatField()),
                ("created_at", models.DateTimeField()),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("admin", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="archived_admin_bank_transactions", to=settings.AUTH_USER_MODEL)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="archived_admin_bank_transactions", to="SmartWagers.event")),
            ],
            options={
                "ordering": ["-archived_at"],
            },
        ),
        migrations.AddIndex(
            model_name="archivedwager",
            index=models.Index(fields=["event", "cashier"], name="archived_wager_event_cashier_idx"),
        ),
        migrations.AddIndex(
            model_name="archivedwager",
            index=models.Index(fields=["event", "fightnum"], name="archived_wager_event_fight_idx"),
        ),
        migrations.AddIndex(
            model_name="archivedtellertransaction",
            index=models.Index(fields=["event", "user"], name="archived_teller_event_user_idx"),
        ),
        migrations.AddIndex(
            model_name="archivedtellertransaction",
            index=models.Index(fields=["event", "transaction_type"], name="archived_teller_event_type_idx"),
        ),
        migrations.AddIndex(
            model_name="archivedadminbanktransaction",
            index=models.Index(fields=["event", "admin"], name="archived_admin_bank_event_admin_idx"),
        ),
        migrations.AddIndex(
            model_name="archivedadminbanktransaction",
            index=models.Index(fields=["event", "transaction_type"], name="archived_admin_bank_event_type_idx"),
        ),
    ]
