# Generated by Django 5.1 on 2026-08-19

from django.db import migrations


MAX_SEQUENCE_VALUE = 999999


def _parse_wager_suffix(transaction_id):
    if not transaction_id or not transaction_id.isdigit():
        return None
    number = int(transaction_id)
    if number <= MAX_SEQUENCE_VALUE:
        return number
    return None


def _parse_prefixed_suffix(transaction_id, prefix):
    if not transaction_id or not transaction_id.startswith(prefix):
        return None
    suffix = transaction_id[len(prefix):]
    if not suffix.isdigit():
        return None
    number = int(suffix)
    if number <= MAX_SEQUENCE_VALUE:
        return number
    return None


def backfill_transaction_generations(apps, schema_editor):
    Wagers = apps.get_model("SmartWagers", "Wagers")
    TellerTransaction = apps.get_model("SmartWagers", "TellerTransaction")
    AdminBankTransaction = apps.get_model("SmartWagers", "AdminBankTransaction")
    TransactionSequence = apps.get_model("SmartWagers", "TransactionSequence")

    Wagers.objects.filter(transactionid__startswith="S").update(sequence_cycle=None)
    Wagers.objects.exclude(transactionid__startswith="S").update(sequence_cycle=0)
    TellerTransaction.objects.update(sequence_cycle=0)
    AdminBankTransaction.objects.update(sequence_cycle=0)

    for txn in AdminBankTransaction.objects.all().iterator():
        if txn.pk > MAX_SEQUENCE_VALUE:
            raise RuntimeError(
                f"AdminBankTransaction pk={txn.pk} exceeds six-digit receipt range; "
                "cannot preserve legacy B IDs."
            )
        txn.transaction_id = f"B{txn.pk:06d}"
        txn.save(update_fields=["transaction_id"])

    wager_max = 0
    for transaction_id in Wagers.objects.values_list("transactionid", flat=True).iterator():
        number = _parse_wager_suffix(transaction_id)
        if number is not None:
            wager_max = max(wager_max, number)

    teller_max = 0
    for transaction_id in TellerTransaction.objects.values_list("transaction_id", flat=True).iterator():
        number = _parse_prefixed_suffix(transaction_id, "R")
        if number is not None:
            teller_max = max(teller_max, number)

    admin_bank_max = 0
    for transaction_id in AdminBankTransaction.objects.values_list("transaction_id", flat=True).iterator():
        number = _parse_prefixed_suffix(transaction_id, "B")
        if number is not None:
            admin_bank_max = max(admin_bank_max, number)

    TransactionSequence.objects.update_or_create(
        key="WAGER", defaults={"value": wager_max, "cycle": 0},
    )
    TransactionSequence.objects.update_or_create(
        key="TELLER", defaults={"value": teller_max, "cycle": 0},
    )
    TransactionSequence.objects.update_or_create(
        key="ADMIN_BANK", defaults={"value": admin_bank_max, "cycle": 0},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0039_transaction_rollover_schema"),
    ]

    operations = [
        migrations.RunPython(
            backfill_transaction_generations,
            migrations.RunPython.noop,
        ),
    ]
