# Generated by Django 5.1 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0040_backfill_transaction_generations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminbanktransaction",
            name="transaction_id",
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AddConstraint(
            model_name="archivedwager",
            constraint=models.UniqueConstraint(
                fields=("sequence_cycle", "transactionid"),
                name="archived_wager_cycle_transactionid_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="archivedtellertransaction",
            constraint=models.UniqueConstraint(
                fields=("sequence_cycle", "transaction_id"),
                name="archived_teller_cycle_transaction_id_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="archivedadminbanktransaction",
            constraint=models.UniqueConstraint(
                fields=("sequence_cycle", "transaction_id"),
                name="archived_admin_bank_cycle_transaction_id_uniq",
            ),
        ),
    ]
