# Generated by Django 5.1 on 2026-09-10 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartWagers", "0045_tellercloseout_cash_count_edit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64)),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")], max_length=16
                    ),
                ),
                (
                    "auth_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "printer_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "printer_address",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("wager", "Wager"),
                            ("payout", "Payout"),
                            ("remit", "Remit"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("payload_json", models.JSONField(default=dict)),
                ("escpos_bytes", models.BinaryField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("printed", "Printed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="archivedadminbanktransaction",
            new_name="SmartWagers_event_i_e66ba7_idx",
            old_name="archived_admin_bank_event_admin_idx",
        ),
        migrations.RenameIndex(
            model_name="archivedadminbanktransaction",
            new_name="SmartWagers_event_i_88c1dc_idx",
            old_name="archived_admin_bank_event_type_idx",
        ),
        migrations.RenameIndex(
            model_name="archivedtellertransaction",
            new_name="SmartWagers_event_i_1b1cea_idx",
            old_name="archived_teller_event_user_idx",
        ),
        migrations.RenameIndex(
            model_name="archivedtellertransaction",
            new_name="SmartWagers_event_i_1ff4a5_idx",
            old_name="archived_teller_event_type_idx",
        ),
        migrations.RenameIndex(
            model_name="archivedwager",
            new_name="SmartWagers_event_i_f6a23f_idx",
            old_name="archived_wager_event_cashier_idx",
        ),
        migrations.RenameIndex(
            model_name="archivedwager",
            new_name="SmartWagers_event_i_679d61_idx",
            old_name="archived_wager_event_fight_idx",
        ),
        migrations.AlterField(
            model_name="archivedadminbanktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("BORROW", "Borrow"), ("REMIT", "Advance")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="archivedtellertransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("REMIT", "Advance"),
                    ("COLLECT", "Borrow"),
                    ("PAYOUT", "Payout"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="printdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="print_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="SmartWagers.printdevice",
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="print_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="printdevice",
            index=models.Index(
                fields=["user", "last_seen"], name="SmartWagers_user_id_e4cd52_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="printdevice",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"), name="printdevice_user_device_id_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="printjob",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="SmartWagers_user_id_bffb70_idx",
            ),
        ),
    ]
