@echo off
REM ============================================================
REM  SmartWagers — Step 1: Create the production .env file
REM  Run this ONCE from the project root: C:\SmartWagers\GameFowl\
REM  Edit the IP address before running.
REM ============================================================

REM ---- EDIT THIS LINE with the actual IP of this server ----
set SERVER_IP=192.168.1.10
REM ----------------------------------------------------------

set ENV_FILE=%~dp0..\\.env

if exist "%ENV_FILE%" (
    echo .env already exists. Delete it manually if you want to regenerate.
    pause
    exit /b 1
)

echo Generating secret key with Python...
for /f "delims=" %%k in ('python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"') do set SECRET_KEY=%%k
if "%SECRET_KEY%"=="" (
    echo ERROR: Could not generate secret key. Is Python installed and on PATH?
    pause
    exit /b 1
)

echo Generating .env file...

(
echo # SmartWagers Production Environment
echo # Generated by deploy\1_setup_env.bat
echo.
echo DJANGO_SECRET_KEY=%SECRET_KEY%
echo DJANGO_DEBUG=False
echo DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,%SERVER_IP%
echo DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost,http://127.0.0.1,http://%SERVER_IP%:8000
echo WAGER_RECEIPT_PRINTING_ENABLED=False
) > "%ENV_FILE%"

echo.
echo .env created at %ENV_FILE%
echo.
echo IMPORTANT: Open .env and verify the SERVER_IP is correct: %SERVER_IP%
echo.
pause
