"""Write production .env without CMD parsing secret characters."""
from __future__ import annotations

import secrets
import string
import sys
from pathlib import Path


def random_secret(length: int = 50) -> str:
    alphabet = string.ascii_letters + string.digits + "!@#%^*-_+="
    return "".join(secrets.choice(alphabet) for _ in range(length))


def random_database_password(length: int = 32) -> str:
    # Keep this URL/shell-safe so the same value can be pasted into psql and
    # the line-oriented .env parser without additional quoting.
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def main() -> int:
    if len(sys.argv) != 3:
        print("Usage: write_env.py <env_path> <server_ip>", file=sys.stderr)
        return 1

    env_path = Path(sys.argv[1])
    server_ip = sys.argv[2].strip()
    if not server_ip:
        print("ERROR: SERVER_IP is empty", file=sys.stderr)
        return 1

    if env_path.exists():
        print(f"ERROR: {env_path} already exists", file=sys.stderr)
        return 1

    secret_key = random_secret()
    lock_signing_key = random_secret()
    postgres_password = random_database_password()

    content = f"""# SmartWagers Production Environment
# Generated by deploy\\1_setup_env.bat

DJANGO_SECRET_KEY={secret_key}
DJANGO_DEBUG=False
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,{server_ip}
DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080,http://{server_ip}:8080
SMARTWAGERS_SERVER_URL=http://{server_ip}:8080
WAGER_RECEIPT_PRINTING_ENABLED=True

# PostgreSQL - local Windows service
DJANGO_DB_ENGINE=postgresql
POSTGRES_DB=smartwagers
POSTGRES_USER=smartwagers_app
POSTGRES_PASSWORD={postgres_password}
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_CONN_MAX_AGE=60
POSTGRES_CONNECT_TIMEOUT=5

# Master lock - REQUIRED in production
MASTER_LOCK_REQUIRED=True
MASTER_LOCK_SIGNING_KEY={lock_signing_key}
MASTER_LOCK_STATE_PATH=C:\\SmartWagers\\data\\master_lock.state
# Set after: python manage.py hash_master_lock_key
MASTER_LOCK_PASSWORD_HASH=
"""
    env_path.write_text(content, encoding="utf-8")
    print(f"Wrote {env_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
